version: '3.7'

volumes:
    prometheus_data: {}

networks:
  front-tier:
  back-tier:

services:
  frontend:
    build: components/frontend/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://frontend/health/" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "8128:80"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: components/backend/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend/health/" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "8129:80"
    depends_on:
      matcher:
        condition: service_healthy

  matcher:
    build: components/matcher/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://matcher/health/" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "8130:80"

  cruncher:
    build: components/cruncher/
    depends_on:
      matcher:
        condition: service_healthy

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager
    volumes:
      - ./alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - '--config.file=/etc/alertmanager/alertmanager.conf'
    ports:
      - 9093:9093

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090
